import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

interface Project {
  name?: string;
  address?: string;
}

interface Payment {
  amount?: number;
  description?: string;
  date?: string;
  id?: string;
}

interface DrawRequestPDFProps {
  project: Project;
  payment: Payment;
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2 solid #000000',
    paddingBottom: 15,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
    marginTop: 5,
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 10,
    borderBottom: '1 solid #cccccc',
    paddingBottom: 5,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  label: {
    fontSize: 11,
    color: '#666666',
    width: 100,
    fontWeight: 'bold',
  },
  value: {
    fontSize: 11,
    color: '#000000',
    flex: 1,
  },
  amountSection: {
    marginTop: 20,
    marginBottom: 30,
    padding: 15,
    backgroundColor: '#f5f5f5',
    borderRadius: 5,
  },
  amountLabel: {
    fontSize: 12,
    color: '#666666',
    marginBottom: 5,
    fontWeight: 'bold',
  },
  amountValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#000000',
  },
  descriptionBox: {
    marginTop: 15,
    padding: 12,
    backgroundColor: '#fafafa',
    borderRadius: 5,
    border: '1 solid #e0e0e0',
    minHeight: 60,
  },
  descriptionText: {
    fontSize: 11,
    color: '#000000',
    lineHeight: 1.5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTop: '1 solid #cccccc',
    paddingTop: 10,
    textAlign: 'center',
  },
  footerText: {
    fontSize: 9,
    color: '#666666',
  },
});

const DrawRequestPDF: React.FC<DrawRequestPDFProps> = ({ project, payment }) => {
  const formatDate = (dateString?: string) => {
    if (!dateString) return 'N/A';
    try {
      const date = new Date(dateString);
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    } catch {
      return dateString;
    }
  };

  const formatCurrency = (amount?: number) => {
    if (amount === null || amount === undefined) return '$0.00';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(amount);
  };

  const currentDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Draw Request / Invoice</Text>
          <Text style={styles.subtitle}>Construction Payment Request</Text>
        </View>

        {/* Project Details Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Project Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Project Name:</Text>
            <Text style={styles.value}>{project.name || 'N/A'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Address:</Text>
            <Text style={styles.value}>{project.address || 'N/A'}</Text>
          </View>
        </View>

        {/* Payment Details Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Payment Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Payment ID:</Text>
            <Text style={styles.value}>{payment.id || 'N/A'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date:</Text>
            <Text style={styles.value}>{formatDate(payment.date)}</Text>
          </View>
        </View>

        {/* Amount Display */}
        <View style={styles.amountSection}>
          <Text style={styles.amountLabel}>Amount Requested</Text>
          <Text style={styles.amountValue}>{formatCurrency(payment.amount)}</Text>
        </View>

        {/* Description Box */}
        {payment.description && (
          <View style={styles.descriptionBox}>
            <Text style={styles.descriptionText}>{payment.description}</Text>
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Generated by Construction App • {currentDate}
          </Text>
        </View>
      </Page>
    </Document>
  );
};

export default DrawRequestPDF;
